# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cusine_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
