# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170410_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
